### ISSUE TITLE
Add support for other data sources

### ISSUE THREAD

**Issue by jdeweese1** [Kamaropoulos/COVID19Py#7]
**Description**
Our API provider has recently added support for pulling data from sources other than John Hopkins University, to now include CSBS. We should also give users of our framework the capability to decide which source they want their app to pull from.

**Solution**
The solution would be to either
1. Add an argument to the `COVID19` constructor for the data source, and every time `_request` is called we look up the data source on the object and pass it with the request OR
2. On each appropriate method, add an optional arg for the data source, and pass that into the `_request` method in the params

I personally lean towards the first solution, I believe it would be a simpler and cleaner implementation than the latter, see below for my thought.

**Code sample**
```Python
class COVID19(object):
    url = ""
    previousData = None
    latestData = None
    __valid_data_sources = ('jhu', 'csbs')

    def __init__(self, url="https://coronavirus-tracker-api.herokuapp.com", data_source='jhu'):
        self.url = url
        if data_source not in self.__valid_data_sources:
            raise Exception()# TODO fix me with better exception
    def _request(self, endpoint: str, params: dict = None):
        if params is None:
            params = {}
        response = requests.get(self.url + endpoint, {**params, 'source': self.data_source})
        response.raise_for_status()
        return response.json()
```
@Kamaropoulos, any thoughts?

**Comment by Kamaropoulos** [comment]
I totally agree!
Since it was added to the API we should definitely implement it here as well.

I also believe the first solution would be a better fit.
Whenever someone is using the library they probably have something specific in mind and they would've already picked the source they want to use. And even if they want to use multiple sources at the same time for whatever reason, they could just instantiate a new object using a different source.
We could implement a way to change the source after setting it the first time but that could potentially mess up the calculations of the changes between requests if anyone ever wants to use that. There hasn't been much work on this feature yet but it could eventually prove useful for some use cases.

**Comment by Kamaropoulos** [comment]
>__valid_data_sources = ('jhu', 'csbs')

![image](https://user-images.githubusercontent.com/10237776/77266617-9ba7ea80-6ca8-11ea-951c-2401aa2fdc43.png)

One issue I see is the potential of adding more sources later on.

While we could hard-code the sources into the library, we would have to manually add any new ones that are added, thus increasing maintenance requirements.

This could be solved in a multitude of ways. Some of them are:
1. Not checking if the source is valid at all.
I don't really like this one because it would make it a bit harder to figure out why something isn't working, since if we try to request data from a source that doesn't exist, the API just returns a `500 Internal Server Error` status without pointing out the actual issue (the source being invalid).
2. Not checking and proposing the addition of a better description for 500 errors.
As a solution to the above issue (not being able to know whether the API request failed because of a server-side issue or an invalid source), we could propose the addition to ExpDev07/coronavirus-tracker-api of a more descriptive error message when someone tries to get data from an invalid source. This way, we can simply check the error message and figure out why it failed.
A problem with this solution is that the user would only know about the problem on the first request they send and not during the library's instantiation.
3. Propose the addition of a way to get all valid sources and check against them.
The problems with the previous two possible solutions could be solved by having a way to check what are the available data sources on the runtime instead of hard-coding them into the library.
The endpoint that would have to be implemented is pretty simple and it's implementation on ExpDev07/coronavirus-tracker-api's side would only have to be changed whenever they add a new data source.
4. Check against a hard-coded list of sources and update them manually.
Inconvenient or not, it is a way.
5. Implement it as per solution 4 in order to get it shipped and then move to solution 3.
The proposal, implementation, and merging of solution 3 into the API's codebase would take a while. To save time, we could implement the 4th solution and then propose the addition of an endpoint to get the available data sources for the API. Then we can just update the implementation to use that one instead of a hard-coded source list.

Personally, I'd go with 5. What do you think @jdeweese1?

**Comment by jdeweese1** [comment]
yep i think what you’ve highlighted there makes sense. i may look into creating an issue and PR for an api endpoint on the server’s repo later

**Comment by ExpDev07** [comment]
Available sources can now be found at the endpoint: https://coronavirus-tracker-api.herokuapp.com/v2/sources. When trying to use a source that's not valid, the API will now return a HTTP status code of ``404``.

**Comment by jdeweese1** [comment]
@Kamaropoulos based on the above I think option 3 is now possible

**Comment by Kamaropoulos** [comment]
Awesome, I'm updating #8 right now.

**Comment by Kamaropoulos** [comment]
Updated and merged. Gonna add some documentation and ship to pypi.

**Comment by Kamaropoulos** [comment]
Released a new version supporting data source selection.
